version: '3'
services:
  redis:
    image: redis
    container_name: redis
    network_mode: "host"
  
  nginx:
    image: nginx
    container_name: nginx
    network_mode: "host"
    volumes:
      - ./nginxConf/nginx.conf:/etc/nginx/nginx.conf

  server:
    build: 
      context: ./backend/
    container_name: DataFeedBackend
    network_mode: "host"
    depends_on:
      - redis
      - nginx
      
  client:
    build:
      context: ./frontend/
    container_name: DataFeedClient
    network_mode: "host"
    depends_on:
      - redis
      - nginx 
      - server

   