version: '3'
services:
  redis:
    image: redis
    container_name: redis
    network_mode: "host"

  server:
    build: 
      context: ./server/
    container_name: DataFeedBackend
    network_mode: "host"
    depends_on:
      - redis
      
  client:
    build:
      context: ./client/
    container_name: DataFeedClient
    network_mode: "host"
    depends_on:
      - redis
      - server
     
  nginx:
    image: mendlik/nginx-cache
    container_name: nginx
    network_mode: "host"
    depends_on:
      - redis
      - client
    volumes:
      - ./nginxConf/nginx.conf:/etc/nginx/nginx.conf
    

   